"""Initial DB schema.

Revision ID: 2cda50f5e35
Revises: None
Create Date: 2014-11-27 17:20:58.601723

"""

# revision identifiers, used by Alembic.
revision = '2cda50f5e35'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
