"""Add date fields.

Revision ID: 36918ba2214
Revises: 3dfddfc9597
Create Date: 2014-11-28 07:46:41.484361

"""

# revision identifiers, used by Alembic.
revision = '36918ba2214'
down_revision = '3dfddfc9597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('report_date', sa.Date(), nullable=True,
                      server_default=sa.func.current_date())
        )
        batch_op.add_column(
            sa.Column('update_datetime', sa.DateTime(), nullable=True,
                      server_default=sa.func.current_timestamp())
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('registration_date', sa.Date(), nullable=True,
                      server_default=sa.func.current_date())
        )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.drop_column('update_datetime')
        batch_op.drop_column('report_date')

    ### end Alembic commands ###
