"""City: remove cap, add pop and activation date.

Revision ID: 3dfddfc9597
Revises: 2cda50f5e35
Create Date: 2014-11-28 07:38:33.991021

"""

# revision identifiers, used by Alembic.
revision = '3dfddfc9597'
down_revision = '2cda50f5e35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('activation_date', sa.Date(), nullable=True,
                      server_default=sa.func.current_date())
        )
        batch_op.add_column(
            sa.Column('population', sa.Integer(), nullable=False,
                      server_default='10000')
        )
        batch_op.drop_column('cap')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('cap', sa.INTEGER(), autoincrement=False, nullable=False,
                      server_default='21011')
        )
        batch_op.drop_column('population')
        batch_op.drop_column('activation_date')

    ### end Alembic commands ###
